# Profiling and Exploration of Clin Trails CSV

In [1]:
import sys
print(sys.executable)+

# confirmed venv python being used

SyntaxError: invalid syntax (2878441632.py, line 2)

In [ ]:
import pandas as pd

In [ ]:
df_trials = pd.read_csv("../data/raw/clin_trials.csv")

In [ ]:
df_trials.head(2)

,Unnamed: 0,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings
0,0,Montefiore Medical Center,OTHER,SPONSOR,Kinesiotape for Edema After Bilateral Total Kn...,"Effect of Kinesiotaping on Edema Management, P...",COMPLETED,2021-10-18,ADULT OLDER_ADULT,"Arthroplasty Complications, Arthroplasty, Repl...",TREATMENT,Kinesio(R)Tape for edema control,"Kinesio(R)Tape is an elastic, cotton tape with...",INTERVENTIONAL,NaN,Change from baseline and during 1-2-day time i...,Edema
1,1,Seoul National University Hospital,OTHER,Unknown,An Open-labeled Trial of Ramipril in Patients ...,An Open-labeled Trial of Ramipril in Patients ...,COMPLETED,2004-10,ADULT OLDER_ADULT,Migraine With Hypertension,TREATMENT,Ramipril,ramipril 2.5mg twice a day,INTERVENTIONAL,PHASE2,headache frequency,Migraine Disorders Hypertension

In [ ]:
df_trials.shape[0]

496615

In [ ]:
df_trials.info()

<class 'pandas.DataFrame'>
RangeIndex: 496615 entries, 0 to 496614
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                496615 non-null  int64
 1   Organization Full Name    496615 non-null  str
 2   Organization Class        496615 non-null  str
 3   Responsible Party         496615 non-null  str
 4   Brief Title               496615 non-null  str
 5   Full Title                496615 non-null  str
 6   Overall Status            496615 non-null  str
 7   Start Date                496615 non-null  str
 8   Standard Age              495730 non-null  str
 9   Conditions                496615 non-null  str
 10  Primary Purpose           496615 non-null  str
 11  Interventions             496615 non-null  str
 12  Intervention Description  496615 non-null  str
 13  Study Type                496615 non-null  str
 14  Phases                    312771 non-null  str
 15  Outcome Measure           496615 non-null  str
 16  Medical Subject Headings  496615 non-null  str
dtypes: int64(1), str(16)
memory usage: 64.4 MB

In [ ]:
df_trials.isnull().sum()

Unnamed: 0                       0
Organization Full Name           0
Organization Class               0
Responsible Party                0
Brief Title                      0
Full Title                       0
Overall Status                   0
Start Date                       0
Standard Age                   885
Conditions                       0
Primary Purpose                  0
Interventions                    0
Intervention Description         0
Study Type                       0
Phases                      183844
Outcome Measure                  0
Medical Subject Headings         0
dtype: int64

In [ ]:
df_trials.duplicated().sum()

np.int64(0)

In [ ]:
df_trials[["Unnamed: 0"]].agg(["min", "max"])

     Unnamed: 0
min           0
max      496614

In [ ]:
df_trials.columns

Index(['Unnamed: 0', 'Organization Full Name', 'Organization Class',
       'Responsible Party', 'Brief Title', 'Full Title', 'Overall Status',
       'Start Date', 'Standard Age', 'Conditions', 'Primary Purpose',
       'Interventions', 'Intervention Description', 'Study Type', 'Phases',
       'Outcome Measure', 'Medical Subject Headings'],
      dtype='str')

In [ ]:
df_trials_dups = (   
    df_trials
    .groupby(['Organization Full Name', 'Organization Class',
       'Responsible Party', 'Brief Title', 'Full Title', 'Overall Status',
       'Start Date', 'Standard Age', 'Conditions', 'Primary Purpose',
       'Interventions', 'Intervention Description', 'Study Type', 'Phases',
       'Outcome Measure', 'Medical Subject Headings'],
        dropna=False)
    .size()
    .reset_index(name="count")
    .query("count > 1")
)

In [ ]:
df_trials_dups.shape[0]

19

In [ ]:
df_trials_dups["count"].sum()

np.int64(922)

In [ ]:
df_trials_dups

,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings,count
32735,Astellas Pharma Inc,INDUSTRY,SPONSOR,A Phase 3 Safety and Efficacy Study of Fovista...,"A Phase 3 Randomized, Double-masked, Controlle...",TERMINATED,2013-08,ADULT OLDER_ADULT,Age-Related Macular Degeneration,TREATMENT,"E10030, ranibizumab, E10030 sham intravitreal ...","Unknown, Unknown, Pressure on the eye with a s...",INTERVENTIONAL,PHASE3,Mean Change in Visual Acuity From Baseline to ...,Macular Degeneration,2
82025,Ceryx Medical Ltd,INDUSTRY,SPONSOR,Respiratory Sinus Arrhythmia Pacing Post-CABG ...,Respiratory Sinus Arrhythmia Pacing Post-CABG ...,NOT_YET_RECRUITING,2024-06-01,ADULT OLDER_ADULT,Heart Failure With Reduced Ejection Fraction,TREATMENT,Atrial pacing with respiratory sinus arrhythmi...,The intervention in this study is a modificati...,INTERVENTIONAL,NaN,Number of arrhythmia episodes per patient duri...,"Heart Failure Arrhythmias, Cardiac Arrhythmia,...",2
106047,"Dipexium Pharmaceuticals, Inc.",INDUSTRY,SPONSOR,Pexiganan Versus Placebo Control for the Treat...,"A Randomized, Double-Blind, Multicenter, Super...",COMPLETED,2014-06,ADULT OLDER_ADULT,Diabetic Foot Infection,TREATMENT,"Topical pexiganan cream 0.8%, Topical placebo ...","14 days of treatment, 14 days of treatment, 14...",INTERVENTIONAL,PHASE3,Number of Participants With Clinical Response,Infections Communicable Diseases Diabetic Foot...,2
121300,FORUM Pharmaceuticals Inc,INDUSTRY,SPONSOR,Study of EVP-6124 (Alpha-7 nAChR) as an Adjunc...,"A Randomized, Double-blind, Placebo-controlled...",COMPLETED,2012-10,ADULT,"Schizophrenia, Impaired Cognition",TREATMENT,"EVP-6124, Placebo","Arms 1, 2, Arm 3",INTERVENTIONAL,PHASE3,Change from Baseline in the Measurement and Tr...,Schizophrenia Cognitive Dysfunction,2
121303,FORUM Pharmaceuticals Inc,INDUSTRY,SPONSOR,Study of the Safety and Effectiveness of Two D...,"A Randomized, Double-blind, Placebo-controlled...",TERMINATED,2013-10,ADULT OLDER_ADULT,"Alzheimer's Disease, Dementia",TREATMENT,"Drug: EVP-6124, Placebo","Unknown, Unknown",INTERVENTIONAL,PHASE3,Change from Baseline in Alzheimer's Disease As...,Alzheimer Disease,2
139723,Glaukos Corporation,INDUSTRY,SPONSOR,Safety and Efficacy Study of Corneal Collagen ...,"A Multi-Center, Randomized, Placebo-Controlled...",COMPLETED,2012-07,CHILD ADULT OLDER_ADULT,Keratoconus,TREATMENT,"riboflavin solution, placebo solution, KXL System","0.12% riboflavin ophthalmic solution, 0.0% rib...",INTERVENTIONAL,PHASE3,Mean change in maximum corneal curvature (Kmax...,Keratoconus,2
172997,InSightec,INDUSTRY,SPONSOR,Blood Brain Barrier (BBB) Disruption Using Exa...,A Safety and Feasibility Study to Evaluate Blo...,RECRUITING,2023-01-04,CHILD ADULT,Brain Tumor,DEVICE_FEASIBILITY,"Exablate, Doxorubicin",Blood Brain Barrier Disruption (BBBD) via Exab...,INTERVENTIONAL,"PHASE1, PHASE2",Adverse Events,Brain Neoplasms,2
200617,King Abdul Aziz Specialist Hospital,NETWORK,SPONSOR,Effect of Bronchoscopy on the Outcome of Patie...,Effect of Bronchoscopy on the Outcome of Patie...,COMPLETED,2020-07-02,ADULT OLDER_ADULT,"ARDS, Septic Shock",TREATMENT,"Meropenem, bronchoscopy, ventilator",all patients in both groups receive meropenam ...,INTERVENTIONAL,"PHASE1, PHASE2",number of patients weaned from the ventilator ...,Sepsis,3
233430,Medicis Global Service Corporation,INDUSTRY,SPONSOR,Topical Antifungal Treatment for Tinea Pedis,"A Randomized, Multi-Center, Double-Blind, Vehi...",COMPLETED,2011-07,CHILD ADULT OLDER_ADULT,Tinea Pedis,TREATMENT,"33525, Placebo","Daily for 14 days, Daily for 14 days",INTERVENTIONAL,PHASE3,Proportion of patients achieving complete clea...,Tinea Tinea Pedis,2
246777,NIH AIDS Clinical Trials Information Service,INDUSTRY,Unknown,"A Double-Blind, Placebo-Controlled Study With ...","A Double-Blind, Placebo-Controlled Study With ...",COMPLETED,Unknown,ADULT OLDER_ADULT,"HIV Infections, Cytopenias",TREATMENT,Epoetin alfa,Unknown,INTERVENTIONAL,NaN,Unknown,Anemia Cytopenia,2
247033,NIH AIDS Clinical Trials Information Service,INDUSTRY,Unknown,Double Blind Study of Thymopentin Effects on P...,Double Blind Study of Thymopentin Effects on P...,COMPLETED,Unknown,ADULT OLDER_ADULT,HIV Infections,TREATMENT,Thymopentin,Unknown,INTERVENTIONAL,NaN,Unknown,Infections Communicable Diseases,2
247091,NIH AIDS Clinical Trials Information Service,INDUSTRY,Unknown,Rifabutin Therapy for the Prevention of Mycoba...,Rifabutin Therapy for the Prevention of Mycoba...,COMPLETED,Unknown,ADULT OLDER_ADULT,"Mycobacterium Avium-intracellulare Infection, ...",TREATMENT,Rifabutin,Unknown,INTERVENTIONAL,NaN,Unknown,Infections Communicable Diseases Bacteremia My...,2
257090,National Institute of Allergy and Infectious D...,NIH,SPONSOR,A Phase I Multicenter Trial to Evaluate the Sa...,A Phase I Multicenter Trial to Evaluate the Sa...,COMPLETED,Unknown,ADULT,HIV Infections,PREVENTION,gp160 Vaccine (MicroGeneSys),Unknown,INTERVENTIONAL,PHASE1,Unknown,HIV Infections,2
279765,Novartis,INDUSTRY,Unknown,Extension Study to Assess the Long-Term Safety...,Extension Study to Assess the Long-Term Safety...,COMPLETED,2004-09,ADULT OLDER_ADULT,Dyspepsia,TREATMENT,Tegaserod,Unknown,INTERVENTIONAL,PHASE3,Long term safety at 6 months.,Dyspepsia,2
298815,Pfizer,INDUSTRY,SPONSOR,Ceftazidime-Avibactam Compared With Doripenem ...,"A Phase III, Randomized, Multicenter, Double-B...",COMPLETED,2012-10,ADULT OLDER_ADULT,Complicated Urinary Tract Infection (cUTI) Inc...,TREATMENT,"Ceftazidime - Avibactam ( CAZ-AVI), Doripenem,...",Ceftazidime 2000 mg and 500 mg of avibactam. P...,INTERVENTIONAL,PHASE3,Patient-reported Symptomatic Response at Day 5...,Infections Communicable Diseases Urinary Tract...,2
328504,Sanofi,INDUSTRY,Unknown,Efficacy and Safety of SR58611A in Patients Wi...,"An Eight-Week, Double-Blind, Placebo Controlle...",COMPLETED,2005-09,ADULT OLDER_ADULT,Major Depressive Disorder,TREATMENT,SR58611A,Unknown,INTERVENTIONAL,PHASE3,17-item Hamilton Depression Rating Scale (HAM-...,Depressive Disorder Depression Depressive Diso...,2
472453,Valeant Pharmaceuticals,INDUSTRY,SPONSOR,A Study Comparing the Efficacy and Safety of I...,"A Phase 3, Multi-Center, Randomized, Double-Bl...",UNKNOWN,2015-09,CHILD ADULT OLDER_ADULT,Acne Vulgaris,TREATMENT,"IDP-121 Lotion, IDP-121 Vehicle Lotion","Investigational Product: IDP-121 Lotion, Compa...",INTERVENTIONAL,PHASE3,Absolute change in inflammatory lesion count f...,Acne Vulgaris,2
475725,Viatris Inc.,INDUSTRY,SPONSOR,Efficacy Study of Nebulized TD-4208 for Chroni...,"A Phase 3, 12-week, Randomized, Double-blind P...",COMPLETED,2015-09,ADULT OLDER_ADULT,Chronic Obstructive Pulmonary Disease (COPD),TREATMENT,"TD-4208, Placebo","Unknown, Unknown",INTERVENTIONAL,PHASE3,Change From Baseline in Trough FEV1 on Day 85,"Lung Diseases Lung Diseases, Obstructive Pulmo...",2
494963,[Redacted],Unknown,Unknown,[Trial of device that is not approved or clear...,[Trial of device that is not approved or clear...,WITHHELD,Unknown,NaN,No conditions listed,Unknown,Unknown,Unknown,Unknown,No phases listed,Unknown,Unknown,885

In [ ]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [ ]:
df_trials_dups.head(1).T

                                                                                                                                                                                                                                                                                                                                                 32735
Organization Full Name                                                                                                                                                                                                                                                                                                             Astellas Pharma Inc
Organization Class                                                                                                                                                                                                                                                                                                                            INDUSTRY
Responsible Party                                                                                                                                                                                                                                                                                                                              SPONSOR
Brief Title                                                                                                                                                                                      A Phase 3 Safety and Efficacy Study of Fovista® (E10030) Intravitreous Administration in Combination With Lucentis® Compared to Lucentis® Monotherapy
Full Title                A Phase 3 Randomized, Double-masked, Controlled Trial to Establish the Safety and Efficacy of Intravitreous Administration of Fovista® (Anti PDGF-B Pegylated Aptamer) Administered in Combination With Lucentis® Compared to Lucentis® Monotherapy in Subjects With Subfoveal Neovascular Age-related Macular Degeneration.
Overall Status                                                                                                                                                                                                                                                                                                                              TERMINATED
Start Date                                                                                                                                                                                                                                                                                                                                     2013-08
Standard Age                                                                                                                                                                                                                                                                                                                         ADULT OLDER_ADULT
Conditions                                                                                                                                                                                                                                                                                                            Age-Related Macular Degeneration
Primary Purpose                                                                                                                                                                                                                                                                                                                              TREATMENT
Interventions                                                                                                                                                                                                                                                                                  E10030, ranibizumab, E10030 sham intravitreal injection
Intervention Description                                                                                                                                                                                                                                                           Unknown, Unknown, Pressure on the eye with a syringe with no needle
Study Type                                                                                                                                                                                                                                                                                                                              INTERVENTIONAL
Phases                                                                                                                                                                                                                                                                                                                                          PHASE3
Outcome Measure                                                                                                                                                                                                                                                                                Mean Change in Visual Acuity From Baseline to 12 Months
Medical Subject Headings                                                                                                                                                                                                                                                                                                          Macular Degeneration
count                                                                                                                                                                                                                                                                                                                                                2

In [ ]:
df_trials[df_trials["Full Title"] == "A Phase 3 Randomized, Double-masked, Controlled Trial to Establish the Safety and Efficacy of Intravitreous Administration of Fovista® (Anti PDGF-B Pegylated Aptamer) Administered in Combination With Lucentis® Compared to Lucentis® Monotherapy in Subjects With Subfoveal Neovascular Age-related Macular Degeneration."]

,Unnamed: 0,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings
179632,179632,Astellas Pharma Inc,INDUSTRY,SPONSOR,A Phase 3 Safety and Efficacy Study of Fovista® (E10030) Intravitreous Administration in Combination With Lucentis® Compared to Lucentis® Monotherapy,"A Phase 3 Randomized, Double-masked, Controlled Trial to Establish the Safety and Efficacy of Intravitreous Administration of Fovista® (Anti PDGF-B Pegylated Aptamer) Administered in Combination With Lucentis® Compared to Lucentis® Monotherapy in Subjects With Subfoveal Neovascular Age-related Macular Degeneration.",TERMINATED,2013-08,ADULT OLDER_ADULT,Age-Related Macular Degeneration,TREATMENT,"E10030, ranibizumab, E10030 sham intravitreal injection","Unknown, Unknown, Pressure on the eye with a syringe with no needle",INTERVENTIONAL,PHASE3,Mean Change in Visual Acuity From Baseline to 12 Months,Macular Degeneration
374419,374419,Astellas Pharma Inc,INDUSTRY,SPONSOR,A Phase 3 Safety and Efficacy Study of Fovista® (E10030) Intravitreous Administration in Combination With Lucentis® Compared to Lucentis® Monotherapy,"A Phase 3 Randomized, Double-masked, Controlled Trial to Establish the Safety and Efficacy of Intravitreous Administration of Fovista® (Anti PDGF-B Pegylated Aptamer) Administered in Combination With Lucentis® Compared to Lucentis® Monotherapy in Subjects With Subfoveal Neovascular Age-related Macular Degeneration.",TERMINATED,2013-08,ADULT OLDER_ADULT,Age-Related Macular Degeneration,TREATMENT,"E10030, ranibizumab, E10030 sham intravitreal injection","Unknown, Unknown, Pressure on the eye with a syringe with no needle",INTERVENTIONAL,PHASE3,Mean Change in Visual Acuity From Baseline to 12 Months,Macular Degeneration

In [ ]:
df_trials_dups[df_trials_dups["Organization Full Name"]=="[Redacted]"].drop_duplicates()

,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings,count
494963,[Redacted],Unknown,Unknown,[Trial of device that is not approved or cleared by the U.S. FDA],[Trial of device that is not approved or cleared by the U.S. FDA],WITHHELD,Unknown,NaN,No conditions listed,Unknown,Unknown,Unknown,Unknown,No phases listed,Unknown,Unknown,885

In [ ]:
pd.reset_option("display.max_columns")
pd.reset_option("display.max_colwidth")
pd.reset_option("display.width")

In [ ]:
df_trials_unique = df_trials.drop(columns=["Unnamed: 0"])
df_trials_unique = df_trials_unique.drop_duplicates()

In [ ]:
df_trials_unique.shape[0]

495712

In [ ]:
df_trials.shape[0]

496615

In [ ]:
print(f"Original rows: {len(df_trials)}")
print(f"Unique rows: {len(df_trials_unique)}")
print(f"Duplicates removed: {len(df_trials) - len(df_trials_unique)}")

Original rows: 496615
Unique rows: 495712
Duplicates removed: 903

## Finding PKs

In [ ]:
total_rows = len(df_trials_unique)

for col in df_trials_unique.columns:
    unique = df_trials_unique[col].nunique(dropna=False)
    print(f"{col:30} {unique:,} / {total_rows:,}")

Organization Full Name         28,083 / 495,712
Organization Class             9 / 495,712
Responsible Party              4 / 495,712
Brief Title                    494,258 / 495,712
Full Title                     483,011 / 495,712
Overall Status                 14 / 495,712
Start Date                     8,787 / 495,712
Standard Age                   7 / 495,712
Conditions                     195,750 / 495,712
Primary Purpose                11 / 495,712
Interventions                  360,696 / 495,712
Intervention Description       383,282 / 495,712
Study Type                     4 / 495,712
Phases                         10 / 495,712
Outcome Measure                415,199 / 495,712
Medical Subject Headings       64,305 / 495,712

In [ ]:
def test_key(df, cols):
    duplicates = (
        df
        .groupby(cols, dropna=False)
        .size()
        .gt(1)
        .sum()
    )

    print(f"{cols}")
    print(f"Duplicate groups: {duplicates}")
    print(f"Candidate key: {'YES' if duplicates == 0 else 'NO'}")

In [ ]:
test_key(df_trials_unique, ["Brief Title", "Organization Full Name"])

['Brief Title', 'Organization Full Name']
Duplicate groups: 811
Candidate key: NO

In [ ]:
df_trials_unique[
    ["Brief Title", "Organization Full Name"]
].value_counts()

Brief Title                                                                                                                                                                         Organization Full Name
Sun Protection Factor Assay                                                                                                                                                         Bayer                                                   14
Vaccine Therapy in Treating Patients With Metastatic Melanoma                                                                                                                       National Cancer Institute (NCI)                          7
PoNS Clinical Experience Program (TBI)                                                                                                                                              Helius Medical Inc                                       5
A Study of Glaucoma Therapy to Treat Open-Angle Glaucoma or Ocular Hypertension                                                                                                     Alcon Research                                           5
Vaccine Therapy With or Without Interleukin-2 in Treating Patients With Metastatic Melanoma                                                                                         National Cancer Institute (NCI)                          5
                                                                                                                                                                                                                                            ..
VitamIn and oXygen Interventions and Cardiovascular Events                                                                                                                          University Hospital Bispebjerg and Frederiksberg         1
A Study to Find the Highest Dose of Imetelstat in Combination With Fludarabine and Cytarabine for Patients With AML, MDS or JMML That Has Come Back or Does Not Respond to Therapy  Children's Oncology Group                                1
Pharmacokinetics of Salmeterol Via HandiHaler® in Healthy Male Volunteers                                                                                                           Boehringer Ingelheim                                     1
Interfascial Pressure Into Ultrasound Guided Anterior Quadratus Lumborum Block Application                                                                                          Bursa Yüksek İhtisas Education and Research Hospital     1
Effects of Action Observation Therapy on Fine Motor Skills of Upper Limb Functions in Chronic Stroke Patients.                                                                      Riphah International University                          1
Name: count, Length: 494799, dtype: int64

In [ ]:
df_trials_unique[
    (df_trials_unique["Brief Title"] == "Vaccine Therapy With or Without Interleukin-2 in Treating Patients With Metastatic Melanoma")
    &
    (df_trials_unique["Organization Full Name"] == "National Cancer Institute (NCI)")
]

,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings
33951,National Cancer Institute (NCI),NIH,Unknown,Vaccine Therapy With or Without Interleukin-2 ...,Phase I/II Study in Patients With Metastatic M...,COMPLETED,1997-04,ADULT OLDER_ADULT,Melanoma (Skin),TREATMENT,"MART-1 antigen, aldesleukin, gp100 antigen","Unknown, Unknown, Unknown",INTERVENTIONAL,"PHASE1, PHASE2",Unknown,Melanoma
255101,National Cancer Institute (NCI),NIH,Unknown,Vaccine Therapy With or Without Interleukin-2 ...,Immunization of Patients With Metastatic Melan...,COMPLETED,1999-04,CHILD ADULT OLDER_ADULT,Melanoma (Skin),TREATMENT,"MART-1 antigen, aldesleukin, gp100 antigen, in...","Unknown, Unknown, Unknown, Unknown",INTERVENTIONAL,PHASE2,Unknown,Melanoma
297526,National Cancer Institute (NCI),NIH,Unknown,Vaccine Therapy With or Without Interleukin-2 ...,Immunization of Patients With Metastatic Melan...,COMPLETED,1999-10,CHILD ADULT OLDER_ADULT,Melanoma (Skin),TREATMENT,"aldesleukin, fowlpox virus vaccine vector, gp1...","Unknown, Unknown, Unknown",INTERVENTIONAL,PHASE2,Unknown,Melanoma
364943,National Cancer Institute (NCI),NIH,Unknown,Vaccine Therapy With or Without Interleukin-2 ...,Phase II Study of DNA Encoding the gp100 Antig...,COMPLETED,1998-09,CHILD ADULT OLDER_ADULT,"Stage IV Melanoma, Recurrent Melanoma",TREATMENT,"gp100 antigen, interleukin-2","Unknown, Unknown",INTERVENTIONAL,PHASE2,Unknown,Melanoma Recurrence
495398,National Cancer Institute (NCI),NIH,Unknown,Vaccine Therapy With or Without Interleukin-2 ...,Treatment of Patients With Metastatic Melanoma...,COMPLETED,1998-11,ADULT OLDER_ADULT,Melanoma (Skin),TREATMENT,"aldesleukin, gp209-2M antigen, incomplete Freu...","Unknown, Unknown, Unknown",INTERVENTIONAL,PHASE2,Unknown,Melanoma

In [ ]:
test_key(df_trials_unique, ["Brief Title", "Organization Full Name", "Full Title", "Start Date"])

['Brief Title', 'Organization Full Name', 'Full Title', 'Start Date']
Duplicate groups: 57
Candidate key: NO

In [ ]:
test_key(df_trials_unique, ["Brief Title", "Organization Full Name", "Full Title", "Start Date", "Interventions", "Responsible Party"])

['Brief Title', 'Organization Full Name', 'Full Title', 'Start Date', 'Interventions', 'Responsible Party']
Duplicate groups: 28
Candidate key: NO

In [ ]:
test_key(df_trials_unique, ["Brief Title", "Organization Full Name", "Full Title", "Start Date", "Interventions", "Conditions", "Phases", "Outcome Measure", "Intervention Description", "Responsible Party"])

['Brief Title', 'Organization Full Name', 'Full Title', 'Start Date', 'Interventions', 'Conditions', 'Phases', 'Outcome Measure', 'Intervention Description', 'Responsible Party']
Duplicate groups: 1
Candidate key: NO

In [ ]:
test_key(df_trials_unique, ["Brief Title", "Organization Full Name", "Responsible Party"])

['Brief Title', 'Organization Full Name', 'Responsible Party']
Duplicate groups: 742
Candidate key: NO

In [ ]:
dups = (
    df_trials_unique
    .groupby(
        [
            "Brief Title",
            "Organization Full Name",
            "Full Title",
            "Start Date",
            "Interventions",
            "Conditions",
            "Phases",
            "Outcome Measure",
            "Intervention Description"
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="count")
    .query("count > 1")
)

dups

,Brief Title,Organization Full Name,Full Title,Start Date,Interventions,Conditions,Phases,Outcome Measure,Intervention Description,count
56955,An Eight-week Study to Evaluate the Efficacy and Safety of Saredutant in Patients With Depression,Sanofi,"An Eight-Week, Multicenter, Double-blind, Placebo-controlled Study Evaluating the Efficacy, Safety, and Tolerability of One Fixed 100 mg Dose of Saredutant in Patients With Major Depressive Disorder.",2005-04,Saredutant succinate (SR48968C),Depressive Disorder,PHASE3,The primary outcome of the study is the change from baseline to Day 56 of treatment in the Hamilton Depression Rating Scale (HAM-D) total score.,Unknown,2
175952,Efficacy Study of PN400 (VIMOVO) Twice Daily and Celebrex Once Daily in Patients With Osteoarthritis,POZEN,"Randomized, Double-Blind, Parallel Group, Placebo-Controlled Multi-Center Study Evaluating the Efficacy of PN400 (VIMOVO) Twice Daily (Bid) and Celecoxib Once Daily (qd) in Patients With Osteoarthritis of the Knee",2008-04,"PN 400 (VIMOVO), celebrex, Placebo, Rescue Antacid",Osteoarthritis,PHASE3,Change in Western Ontario and McMaster Universities (WOMAC) Pain Questionnaire Subscore From Baseline Change in Western Ontario and McMaster Universities (WOMAC) Function Questionnaire Subscore From Baseline Change in Patient Global Assessment (PGA) Subscore From Baseline,"500 mg naproxen/20 mg esomeprazole bid, 200 mg celecoxib qd, sugar pill bid, Antacid Tablets",2
204400,Evaluation of the PillCam™ Colon Capsule Endoscopy (PCCE) Preparation and Procedure,Medtronic - MITG,Evaluation of the PillCam Colon Capsule Endoscopy Preparation and Procedure,2008-02,Unknown,Colonic Diseases,Unknown,Colon cleansing level score Number of colon capsules excreted over time,Unknown,2

In [ ]:
cols = [
    "Brief Title",
    "Organization Full Name",
    "Full Title",
    "Start Date",
    "Interventions",
    "Conditions",
    "Phases",
    "Outcome Measure",
    "Intervention Description"
]

duplicate_rows = df_trials_unique.merge(
    dups[cols],
    on=cols,
    how="inner"
)

duplicate_rows

,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings
0,Sanofi,INDUSTRY,Unknown,An Eight-week Study to Evaluate the Efficacy and Safety of Saredutant in Patients With Depression,"An Eight-Week, Multicenter, Double-blind, Placebo-controlled Study Evaluating the Efficacy, Safety, and Tolerability of One Fixed 100 mg Dose of Saredutant in Patients With Major Depressive Disorder.",COMPLETED,2005-04,ADULT,Depressive Disorder,TREATMENT,Saredutant succinate (SR48968C),Unknown,INTERVENTIONAL,PHASE3,The primary outcome of the study is the change from baseline to Day 56 of treatment in the Hamilton Depression Rating Scale (HAM-D) total score.,Depressive Disorder Depression
1,POZEN,INDUSTRY,SPONSOR,Efficacy Study of PN400 (VIMOVO) Twice Daily and Celebrex Once Daily in Patients With Osteoarthritis,"Randomized, Double-Blind, Parallel Group, Placebo-Controlled Multi-Center Study Evaluating the Efficacy of PN400 (VIMOVO) Twice Daily (Bid) and Celecoxib Once Daily (qd) in Patients With Osteoarthritis of the Knee",COMPLETED,2008-04,ADULT OLDER_ADULT,Osteoarthritis,TREATMENT,"PN 400 (VIMOVO), celebrex, Placebo, Rescue Antacid","500 mg naproxen/20 mg esomeprazole bid, 200 mg celecoxib qd, sugar pill bid, Antacid Tablets",INTERVENTIONAL,PHASE3,Change in Western Ontario and McMaster Universities (WOMAC) Pain Questionnaire Subscore From Baseline Change in Western Ontario and McMaster Universities (WOMAC) Function Questionnaire Subscore From Baseline Change in Patient Global Assessment (PGA) Subscore From Baseline,Osteoarthritis
2,Sanofi,INDUSTRY,SPONSOR,An Eight-week Study to Evaluate the Efficacy and Safety of Saredutant in Patients With Depression,"An Eight-Week, Multicenter, Double-blind, Placebo-controlled Study Evaluating the Efficacy, Safety, and Tolerability of One Fixed 100 mg Dose of Saredutant in Patients With Major Depressive Disorder.",COMPLETED,2005-04,ADULT,Depressive Disorder,TREATMENT,Saredutant succinate (SR48968C),Unknown,INTERVENTIONAL,PHASE3,The primary outcome of the study is the change from baseline to Day 56 of treatment in the Hamilton Depression Rating Scale (HAM-D) total score.,Depressive Disorder Depression
3,POZEN,INDUSTRY,Unknown,Efficacy Study of PN400 (VIMOVO) Twice Daily and Celebrex Once Daily in Patients With Osteoarthritis,"Randomized, Double-Blind, Parallel Group, Placebo-Controlled Multi-Center Study Evaluating the Efficacy of PN400 (VIMOVO) Twice Daily (Bid) and Celecoxib Once Daily (qd) in Patients With Osteoarthritis of the Knee",COMPLETED,2008-04,ADULT OLDER_ADULT,Osteoarthritis,TREATMENT,"PN 400 (VIMOVO), celebrex, Placebo, Rescue Antacid","500 mg naproxen/20 mg esomeprazole bid, 200 mg celecoxib qd, sugar pill bid, Antacid Tablets",INTERVENTIONAL,PHASE3,Change in Western Ontario and McMaster Universities (WOMAC) Pain Questionnaire Subscore From Baseline Change in Western Ontario and McMaster Universities (WOMAC) Function Questionnaire Subscore From Baseline Change in Patient Global Assessment (PGA) Subscore From Baseline,Osteoarthritis
4,Medtronic - MITG,INDUSTRY,SPONSOR,Evaluation of the PillCam™ Colon Capsule Endoscopy (PCCE) Preparation and Procedure,Evaluation of the PillCam Colon Capsule Endoscopy Preparation and Procedure,COMPLETED,2008-02,ADULT OLDER_ADULT,Colonic Diseases,Unknown,Unknown,Unknown,OBSERVATIONAL,Unknown,Colon cleansing level score Number of colon capsules excreted over time,Colonic Diseases
5,Medtronic - MITG,INDUSTRY,SPONSOR,Evaluation of the PillCam™ Colon Capsule Endoscopy (PCCE) Preparation and Procedure,Evaluation of the PillCam Colon Capsule Endoscopy Preparation and Procedure,COMPLETED,2008-02,ADULT,Colonic Diseases,Unknown,Unknown,Unknown,OBSERVATIONAL,Unknown,Colon cleansing level score Number of colon capsules excreted over time,Colonic Diseases

In [ ]:
duplicate_rows = duplicate_rows.sort_values(cols)

duplicate_rows

,Organization Full Name,Organization Class,Responsible Party,Brief Title,Full Title,Overall Status,Start Date,Standard Age,Conditions,Primary Purpose,Interventions,Intervention Description,Study Type,Phases,Outcome Measure,Medical Subject Headings
0,Sanofi,INDUSTRY,Unknown,An Eight-week Study to Evaluate the Efficacy and Safety of Saredutant in Patients With Depression,"An Eight-Week, Multicenter, Double-blind, Placebo-controlled Study Evaluating the Efficacy, Safety, and Tolerability of One Fixed 100 mg Dose of Saredutant in Patients With Major Depressive Disorder.",COMPLETED,2005-04,ADULT,Depressive Disorder,TREATMENT,Saredutant succinate (SR48968C),Unknown,INTERVENTIONAL,PHASE3,The primary outcome of the study is the change from baseline to Day 56 of treatment in the Hamilton Depression Rating Scale (HAM-D) total score.,Depressive Disorder Depression
2,Sanofi,INDUSTRY,SPONSOR,An Eight-week Study to Evaluate the Efficacy and Safety of Saredutant in Patients With Depression,"An Eight-Week, Multicenter, Double-blind, Placebo-controlled Study Evaluating the Efficacy, Safety, and Tolerability of One Fixed 100 mg Dose of Saredutant in Patients With Major Depressive Disorder.",COMPLETED,2005-04,ADULT,Depressive Disorder,TREATMENT,Saredutant succinate (SR48968C),Unknown,INTERVENTIONAL,PHASE3,The primary outcome of the study is the change from baseline to Day 56 of treatment in the Hamilton Depression Rating Scale (HAM-D) total score.,Depressive Disorder Depression
1,POZEN,INDUSTRY,SPONSOR,Efficacy Study of PN400 (VIMOVO) Twice Daily and Celebrex Once Daily in Patients With Osteoarthritis,"Randomized, Double-Blind, Parallel Group, Placebo-Controlled Multi-Center Study Evaluating the Efficacy of PN400 (VIMOVO) Twice Daily (Bid) and Celecoxib Once Daily (qd) in Patients With Osteoarthritis of the Knee",COMPLETED,2008-04,ADULT OLDER_ADULT,Osteoarthritis,TREATMENT,"PN 400 (VIMOVO), celebrex, Placebo, Rescue Antacid","500 mg naproxen/20 mg esomeprazole bid, 200 mg celecoxib qd, sugar pill bid, Antacid Tablets",INTERVENTIONAL,PHASE3,Change in Western Ontario and McMaster Universities (WOMAC) Pain Questionnaire Subscore From Baseline Change in Western Ontario and McMaster Universities (WOMAC) Function Questionnaire Subscore From Baseline Change in Patient Global Assessment (PGA) Subscore From Baseline,Osteoarthritis
3,POZEN,INDUSTRY,Unknown,Efficacy Study of PN400 (VIMOVO) Twice Daily and Celebrex Once Daily in Patients With Osteoarthritis,"Randomized, Double-Blind, Parallel Group, Placebo-Controlled Multi-Center Study Evaluating the Efficacy of PN400 (VIMOVO) Twice Daily (Bid) and Celecoxib Once Daily (qd) in Patients With Osteoarthritis of the Knee",COMPLETED,2008-04,ADULT OLDER_ADULT,Osteoarthritis,TREATMENT,"PN 400 (VIMOVO), celebrex, Placebo, Rescue Antacid","500 mg naproxen/20 mg esomeprazole bid, 200 mg celecoxib qd, sugar pill bid, Antacid Tablets",INTERVENTIONAL,PHASE3,Change in Western Ontario and McMaster Universities (WOMAC) Pain Questionnaire Subscore From Baseline Change in Western Ontario and McMaster Universities (WOMAC) Function Questionnaire Subscore From Baseline Change in Patient Global Assessment (PGA) Subscore From Baseline,Osteoarthritis
4,Medtronic - MITG,INDUSTRY,SPONSOR,Evaluation of the PillCam™ Colon Capsule Endoscopy (PCCE) Preparation and Procedure,Evaluation of the PillCam Colon Capsule Endoscopy Preparation and Procedure,COMPLETED,2008-02,ADULT OLDER_ADULT,Colonic Diseases,Unknown,Unknown,Unknown,OBSERVATIONAL,Unknown,Colon cleansing level score Number of colon capsules excreted over time,Colonic Diseases
5,Medtronic - MITG,INDUSTRY,SPONSOR,Evaluation of the PillCam™ Colon Capsule Endoscopy (PCCE) Preparation and Procedure,Evaluation of the PillCam Colon Capsule Endoscopy Preparation and Procedure,COMPLETED,2008-02,ADULT,Colonic Diseases,Unknown,Unknown,Unknown,OBSERVATIONAL,Unknown,Colon cleansing level score Number of colon capsules excreted over time,Colonic Diseases

# Profiling Conclusions:

No clear PK found, duplicates removed

## -- These do not appear to be duplicates, they seem to be redacted instead (possibly masked for some users), they should not be all removed
But df_trials_dups[df_trials_dups["Organization Full Name"]=="[Redacted]"].drop_duplicates() 

- Regarding data quality, some spelling mistakes cause 'duplicates' with Description Fields
    - will need to check how to deal with those

- Will be using a surrogate key
- Get rid of first col which seems leftover from csv parsing, remove duplicates, save redacted, add surrogate key, move forward to noramlized db schema